### ISSUE TITLE
UI für Konfigurationspage

### ISSUE THREAD

**Issue by sihingbenni** [janelucia/rob-temi-robo#12]
Beim Start der App muss die Möglichkeit bestehen bestimmte Einstellungen aus der Datenbank zu treffen.

Zum Beispiel muss man dem Roboter sagen auf welchem Stockwerk er steht, falls er mehrere Datenbanken Einträge besitzt.

Möglich denkbar wären dafür Dropdown Menüs. 
Auch gut wäre es wenn auf diesem Bildschirm Warnungen angezeigt werden, falls mehr als eine Route erkannt wird.

Akzeptanzkriterien:
* Datenbank testen:
  * gibt es einen Start- und einen Endpunkt? (to- und from-transfers)
  * gibt es mehr als einen Start- und Endpunkt? -> Fehler geht nicht -> kein Dropdown für die Transfers
  * Verzweigungen? - haben wir mehr als 2mal einen Punkt in From und ist dieser nicht der Startpunkt.
* Auswahl automatisch - überspringen, wenn es nur eine mögliche Tour gibt, die übereinstimmt (Karte stimmt überein)
  * Verifizieren, dass die Daten aus der Karte mit den Daten aus der Datenbank übereinstimmt - Fehlermeldung (Datenbank ist kaputt)
  * Places automatisch - möglich?
* Befüllen der important und unimportant List der Locations
* mögliche Touren zusammenstellen

**Comment by janelucia** [comment]
close as done
