### ISSUE TITLE
Eigene "Tour" ermöglichen

### ISSUE THREAD

**Issue by sihingbenni** [janelucia/rob-temi-robo#16]
Akzeptanzkriterien
* Erst Liste der Locations anzeigen und dem User ermöglichen ein Exponat auszuwählen ✔️ 
* Robo fährt zu dem Exponat und nutzt die Ansicht von der Location bei der Führung
* nach Ende vom Exponat fragt der Robo erneut nach dem nächsten Exponat oder ob abgebrochen werden soll

**Comment by janelucia** [comment]
Close as done
